#ifndef SSU_MONITOR_DEFINE_H
#define SSU_MONITOR_DEFINE_H

#define SSU_MONITOR_MAX_PATH 4096
#define SSU_MONITOR_MAX_FILENAME 255

#define SSU_MONITOR_SETTING_FILE "monitor_list.txt"

#define SSU_MONITOR_UMASK 0

#endif