#ifndef SSU_UTIL_DEFINE_H
#define SSU_UTIL_DEFINE_H

#define SSU_UTIL_MAX_PATH_BUF_SZ 4096
#define SSU_UTIL_MAX_FILENAME_BUF_SZ 256
#define SSU_UTIL_FILE_META_LEN 13
#define SSU_UTIL_MKDIR_AUTH (S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH)
#define SSU_UTIL_MKFILE_AUTH (S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH)

#endif
